apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dnsmasq-controller-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dnsmasq-controller-leader-election
subjects:
- kind: ServiceAccount
  name: dnsmasq-controller
  namespace: default
